### ISSUE TITLE
Wrong toolchain when using WSL

### ISSUE THREAD

**Issue by Dodecahedr0x** [FuelLabs/fuelup#111] opened 2022-07-21 18:19 UTC
Hi,

I installed `fuelup` and `forc` today and managed to build and deploy a project.
After reopening a terminal, I'm now getting the following error:
```
/home/Dodecahedr0x/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/forc: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/Dodecahedr0x/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/forc)
```

I'm using the Windows Subsystem Linux (WSL) running a 18.04 Ubuntu.
I think this could be due to the default rustup toolchain being `stable-x86_64-unknown-linux-gnu (default)` instead of something `x86_64-linux-gnu`.

**Comment by mitchmindtree** [comment] 2022-07-22 07:18
Thanks for the issue @Dodecahedr0x!

I've transferred this from the Sway repo over to the fuelup repo as I think it's likely more suited here.

> After reopening a terminal, I'm now getting the following error

Interesting, this makes me wonder if the issue is `PATH` related. Before you re-opened the terminal, are you sure  you were using the `fuelup`-installed `forc` instance? Is there a chance you might have been using an older `forc` instance installed via some other means like `cargo install forc`?

Would you mind also providing the exact command you used to produce the `forc` error? E.g. does it happen when you run `forc --help`? Or only when running a particular command?

@JoshuaBatty is also on WSL - he might have some insight?

**Comment by Dodecahedr0x** [comment] 2022-07-22 08:02
Thanks for your reply,

I have the path to `~/.fuelup/bin` in my `PATH`, I ran `cargo uninstall forc` and checked that the `.cargo/bin` repo does not have anything named `forc` in it.

To produce this error I ran `forc new my_project` but i get the same error (3 times per command) when I type `forc --help` or any other command.

I installed a new Ubuntu 18.04 on the WSL1 however and it worked and keeps working so I guess it's caused by some of the differences in how WSL1 and WSL2 work...

**Comment by bingcicle** [comment] 2022-07-22 14:59
I am able to reproduce it now on a Linode Ubuntu 18.04 instance, running into the same error. It seems like glibc_2.27 is the latest supported version on Ubuntu 18.04, and `forc` executable requires glibc_2.29, since it was compiled and distributed using Ubuntu 20.04. I think a quick fix would be to use Ubuntu >20.04 instead, but I will continue looking into this.

**Comment by carletex** [comment] 2022-10-19 14:29
Hey there!

I'm having the same issue. I'm on Linux Mint 19.3 (Ubuntu 18.04 base).

`forc --help` returns:
```
/home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/forc: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/forc)
/home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/forc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/forc)
/home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/forc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/forc)
```

`fule-core --help` returns:
```
/home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/fuel-core: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/fuel-core)
/home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/fuel-core: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/fuel-core)
/home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/fuel-core: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/fuel-core)
/home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/fuel-core: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/my-user/.fuelup/toolchains/latest-x86_64-unknown-linux-gnu/bin/fuel-core)
``` 

There are some guides online on how to update to GLIBC_2.29 on Ubuntu 18.04, but seems like a dangerous update and it breaks the OS for some people.

I'm guessing this a tricky thing to fix on your side.

Thanks!

**Comment by bingcicle** [comment] 2022-10-19 15:19
This issue is a result of our usage of GitHub runners to build and release our binaries, and they currently all run on [`ubuntu-latest`](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) which is `ubuntu-20.04`, which would use the glibc version available on the system. Unfortunately, since the binaries are dynamically linked, this means that the binaries try to also use the same glibc version even on an earlier Linux distro version. GitHub is also [deprecating the `ubuntu-18.04`](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) runners soon, so we can't simply downgrade them :/

The immediate solution(s) to this issue would be to either:
a) upgrade to Ubuntu 20.04 if possible, or
b) clone the repos, compile and use both `forc` and `fuel-core` from source.

Both solutions aren't pretty :sweat_smile: 

I de-prioritized this issue for a bit to work on other things but I will start to actively find a workaround for this.

**Comment by carletex** [comment] 2022-10-19 16:22
Thanks for the quick response @bingcicle !!

I was able to install fuelup & fuel-core from source.

To have the same setup for `forc` as in the quickstart guide: 

`This will install forc, forc-client, forc-fmt, forc-explore, forc-lsp`

Which repos should I clone & compile? I see the `forc-client` and `forc-explore` repos, but not the other ones.

Thanks!

**Comment by bingcicle** [comment] 2022-10-20 02:47
Those should all be in the [Sway repo](https://github.com/FuelLabs/sway). `forc-client` was going to be extracted out of that repo, but we abandoned that plan, and `forc-explore` is in the process of being extracted out. Most of what you need to develop should be available within the Sway repo itself!

**Comment by bingcicle** [comment] 2023-04-03 07:49
Closing due to inactivity - pleaes reopen if this is still an issue.

**Closed by bingcicle** 2023-04-03 07:49 UTC
Labels: bug
