### ISSUE TITLE
Add integration testing for version sets that must pass before updating version index

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuelup#83] opened 2022-06-23 00:56 UTC
Related to #66, followup to #75.

I wonder if there's some way we can re-use the E2E tests from the Sway repo for this? E.g. fetch the sway repo, patch the `forc` and `fuel-core` versions used and run those tests?

We only really need the tests that check the integration of `forc` and `fuel-core`, so e.g. the contract deployment ones, running scripts and checking their results, etc. Perhaps we could filter out the language tests.

Alternatively, we can start adding our own integration tests here. That said, I can't think of many `forc`+`fuel-core` integration tests that would be only be beneficial here that would not *also* be beneficial at the Sway repo. It would be a shame to have some test here that could have been added to Sway and caught some incompatibility bug earlier in the release process.

**Comment by binggh** [comment] 2022-06-23 05:42
Correct me if I'm wrong: the e2e tests in the sway repo [here](https://github.com/FuelLabs/sway/tree/master/test/src/e2e_vm_tests) are enough to guarantee that the latest `forc` release works with whatever the version of `fuel-core` was being used in the tests (especially since there are tests that run on the config `run_on_node`), however it is not enough to guarantee that if a new `fuel-core` version was released without a new `forc` release, we don't know for sure that the new `fuel-core` is compatible - hence the need for this issue.

So the problem is again the decision of where these checks live like we discussed in #66, whether it should be a push-based check or a pull-based check. 

If we opt for a push-based check, I imagine we could have `fuel-core`, on release, trigger a `workflow_dispatch` event within the `sway_repo` to run integration tests with the new `fuel-core` version somehow. Then we'd need a way to communicate whether it passed or failed to fuelup.

The alternative is to use this repo to, again, poll for new releases, checkout the code and run them on the CI here(?). Again, it seems like both solutions aren't perfect but I think it'd be messier if we left it up to the `sway` or `fuel-core` repos. I think sticking to the maxim of `ignorance of fuelup` is a good way to go here?

**Comment by binggh** [comment] 2022-06-23 05:50
> It would be a shame to have some test here that could have been added to Sway and caught some incompatibility bug earlier in the release process.

Agreed, I think tests should be written in the Sway repo, and we just need to decide if we want to check compatibility here (by pulling code from both repos and running tests), or in the Sway repo.

**Comment by mitchmindtree** [comment] 2022-06-24 06:20
> Correct me if I'm wrong: the e2e tests in the sway repo [here](https://github.com/FuelLabs/sway/tree/master/test/src/e2e_vm_tests) are enough to guarantee that the latest forc release works with whatever the version of fuel-core was being used in the tests (especially since there are tests that run on the config run_on_node), however it is not enough to guarantee that if a new fuel-core version was released without a new forc release, we don't know for sure that the new fuel-core is compatible - hence the need for this issue.

Yes exactly :+1: 

> So the problem is again the decision of where these checks live like we discussed in https://github.com/FuelLabs/fuelup/issues/66, whether it should be a push-based check or a pull-based check.

I think it might make sense to pull for these, particularly as we only need to test upon detecting a new release from either `fuel-core` or `forc`. I'm imagining something along the lines of:

1. Cron checking for new releases
2. New release detected
3. Work out `fuel-core` and `forc` versions to test together
4. **Fetch sway repo** (probably another good case for using shell script :smiling_face_with_tear:)
5. Run the E2E tests with `forc` and `fuel-core` versions to test. Possibly use a regex to filter for the integration tests.
6. Upon success, update toolchain versions in the index.
7. Upon failure, leave toolchain versions as they are and record somewhere the version set that failed (this should be checked before running the tests, otherwise if there's a failure the cron-job will just keep running the same failed tests over and over).

^ @binggh what are your thoughts on something like this?

**Comment by binggh** [comment] 2022-06-24 07:44
Sounds good! Unfortunate that we have to once again rely on scripting for this but given that it's a part of the CI and not really a part of the `fuelup` package itself it seems acceptable to me.

I'd probably implement it somewhere along the lines of the current `index-versions` script as well - checking for new releases on a 30 minute time interval.

Just to be clear - is it ok if the tests are run against a `fuel-core` binary, or is it necessary to build `fuel-core` from source, or run it within docker just like how the Sway repo does it as well? Or was running from docker out of necessity?

**Comment by mitchmindtree** [comment] 2022-06-24 08:26
> Just to be clear - is it ok if the tests are run against a fuel-core binary, or is it necessary to build fuel-core from source, or run it within docker just like how the Sway repo does it as well? Or was running from docker out of necessity?

Whatever's easiest I think! I don't use docker and haven't had any troubles when running the E2E tests locally.

**Closed** 2022-07-18 23:23 UTC
Labels: ci, testing
