### ISSUE TITLE
Could `wallet new` command support no-password?

### ISSUE THREAD

**Issue by lispking** [FuelLabs/fuelup#660] opened 2024-09-10 08:37 UTC
Could you consider supporting the "no-password" parameter when executing "forc wallet new", so that it is convenient for scripts to directly generate wallets without a password?

**Comment by sdankel** [comment] 2024-09-10 18:16
Duplicate of https://github.com/FuelLabs/forc-wallet/issues/202

**Closed by sdankel** 2024-09-10 18:16 UTC
