### ISSUE TITLE
MULTIPLY INCREMENT USING SWAY LANGUAGE

### ISSUE THREAD

**Issue by Elexy101** [FuelLabs/fuelup#571] opened 2024-02-18 09:26 UTC
I just deploy a simple muliply increment on Fuel for basic usage I built using the Sway programming language. Hope this push me further developing a simple mathematical game on FuelLab....

Contract id: 0xf17794e7f39c6c9f4893cf4f4032aaaee16a1a5d0a8f7fef8746985e6310cf48

Fuel address: fuel1wkrf9vu2g6pj802ekxlx79rvr50mnn7whp5k6uz64fw8lrucrj4srw3v3l

![Screenshot from 2024-02-18 10-26-13](https://github.com/FuelLabs/fuelup/assets/24855083/ac0bb5de-d581-41a2-b0cc-f0bb2086ae88)

**Comment by JoshuaBatty** [comment] 2024-06-17 06:03
I'm not sure what the issue is here as it relates to fuelup. Closing.

**Closed by JoshuaBatty** 2024-06-17 06:03 UTC
